# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Community Automation 

on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
#   pull_request_review:
#     types: 
#       - submitted
#   schedule:
#     - cron: '0 4 * * MON-FRI'
  workflow_dispatch:
  
jobs:
  job1:
    name: Output Test Path From Json
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: MT-QA-Automation/Community
        token: ${{ secrets.MT_RF_REPO_PAT }}    
    - id: set_matrix
      run: |
        content="$(cat test-path.json)"
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        echo "::set-output name=json::$content"
    outputs: 
      matrix: ${{ steps.set_matrix.outputs.json }}
  job2:
    needs: job1
    name: DJuarbal
    runs-on: windows-latest
    env:
      #Web_Driver: Chrome
      Web_Driver: Firefox
    strategy:
      fail-fast: false
      matrix: 
        include: ${{fromJson(needs.job1.outputs.matrix).d-juarbal}}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: MT-QA-Automation/Community
        token: ${{ secrets.MT_RF_REPO_PAT }}
    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Python Libraries
      run: pip install -r requirements.txt
    - name: Install Chromedriver
      if: ${{ env.Web_Driver == 'Chrome' }}
      uses: nanasess/setup-chromedriver@master
    - name: Install Geckodriver
      if: ${{ env.Web_Driver == 'Firefox' }}
      uses: browser-actions/setup-geckodriver@latest
    - name: Adjust Resolution 
      run: Set-DisplayResolution -Width 1920 -Height 1080 -Force
    - name: Run Robot Tests 
      run: robot -T -d "Results" -r NONE -e Deferred "${{matrix.test-suite}}"
    - name: Upload Artifacts
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.name}} Logs
        path: Results
#   job3:
#     needs: job1
#     name: DemoTest
#     runs-on: windows-latest
#     strategy:
#       fail-fast: false
#       matrix: 
#         include: ${{fromJson(needs.job1.outputs.matrix).demo-test}}
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
#       with:
#         repository: MT-QA-Automation/Community
#         token: ${{ secrets.MT_RF_REPO_PAT }}
#     - name: Setup Python 3.9
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.9
#     - name: Install Python Libraries
#       run: pip install -r requirements.txt
#     - name: Install Chromedriver
#       uses: nanasess/setup-chromedriver@master
#     - name: Install Geckodriver
#       uses: browser-actions/setup-geckodriver@latest
#     - name: Adjust Resolution 
#       run: Set-DisplayResolution -Width 1920 -Height 1080 -Force
#     - name: Run Robot Tests 
#       run: robot -T -d "Results" -r NONE -e Deferred "${{matrix.test-suite}}"
#     - name: Upload Artifacts
#       if: always()
#       uses: actions/upload-artifact@v2
#       with:
#         name: ${{matrix.name}} Logs
#         path: Results
