# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test  

on:
  workflow_dispatch:
  
jobs:
  job1:
    name: Test
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix: 
        include:
          - name: 'Login' 
            test-suite: 'Login'
    steps:
    - name: Install RF Dependencies
      uses: MT-QA-Automation/Actions@v1
    - name: Run Robot Tests 
      run: |
        robot -d "Results" -r NONE -e Deferred "Academy\${{matrix.test-suite}}"
    - name: Upload Artifacts
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.name}} Logs
        path: Results
