# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Academy Automation 

on:
  workflow_dispatch:
  
jobs:
  job0:
    name: Output Json File
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - id: set_matrix
#       run: |
#         content= cat test-path.json
#         content="${content//'%'/'%25'}"
#         content="${content//$'\n'/'%0A'}"
#         content="${content//$'\r'/'%0D'}"
#         echo "::set-output name=json::$content"
      run: |
        JSON=$(cat test-path.json)
        echo "::set-output name=json::${JSON//'%'/'%25'}"
    - run: |
        echo "${{fromJson(steps.set_matrix.outputs.json)}}"
    outputs: 
      matrix: ${{ steps.set_matrix.outputs.json }}
  job1:
    needs: job0
    name: Academy
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.job0.outputs.matrix)}}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: MT-QA-Automation/Robot-Framework-Test
        token: ${{ secrets.MT_RF_REPO_PAT }}
    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Python Libraries
      run: pip install -r requirements.txt
    - name: Install Chromedriver
      uses: nanasess/setup-chromedriver@master    
    - name: Adjust Resolution 
      run: Set-DisplayResolution -Width 1920 -Height 1080 -Force
    - name: Run Robot Tests 
      run: robot -d "Results" -r NONE -e Deferred "Academy\${{matrix.test-suite}}"
    - name: Upload Artifacts
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.name}} Logs
        path: Results
